# Generated by Django 2.2.17 on 2020-11-17 18:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 17, 18, 44, 26, 104987, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
