# Generated by Django 2.2.17 on 2020-11-16 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
