# Generated by Django 2.2.17 on 2020-11-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsula', '0003_auto_20201116_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='project_date',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
    ]
